"""Visibility-checked FR3 joint targets for automatic camera calibration."""

from __future__ import annotations

import math
from typing import Sequence


JOINT_NAMES = tuple(f"fr3_joint{index}" for index in range(1, 8))

# These poses are every second point of the 24-frame trajectory generated by
# tests/test_sim_calibration.py.  With the D415 opposite the hand as modelled by
# that test, the complete printed tag remains inside the RGB image at each pose.
AUTO_WAYPOINTS = (
    (-0.392613, 0.063869, 0.093943, -1.662252, 0.800836, 2.418347, -2.210767),
    (-0.299113, 0.156121, 0.012109, -1.766856, 0.839798, 2.324672, -2.317067),
    (-0.230666, 0.096540, -0.239369, -1.915855, 0.384672, 2.219175, -2.726579),
    (-0.205613, -0.055293, -0.157535, -1.960250, 0.345710, 2.130125, -2.990900),
    (-0.230666, -0.147545, 0.093943, -1.855646, 0.800836, 2.081381, -2.923491),
    (-0.299113, -0.087964, 0.012109, -1.706647, 0.839798, 2.086005, -2.513979),
    (-0.392613, 0.063869, -0.239369, -1.662252, 0.384672, 2.142759, -2.210767),
    (-0.486113, 0.156121, -0.157535, -1.766856, 0.345710, 2.236434, -2.317067),
    (-0.554560, 0.096540, 0.093943, -1.915855, 0.800836, 2.341931, -2.726579),
    (-0.579613, -0.055293, 0.012109, -1.960250, 0.839798, 2.430981, -2.990900),
    (-0.554560, -0.147545, -0.239369, -1.855646, 0.384672, 2.479725, -2.923491),
    (-0.486113, -0.087964, -0.157535, -1.706647, 0.345710, 2.475101, -2.513979),
)

# Conservative limits from the FR3 model.  A small margin keeps programmed
# points away from hard stops even if the upstream limits change slightly.
FR3_JOINT_LIMITS = (
    (-2.7437, 2.7437),
    (-1.7837, 1.7837),
    (-2.9007, 2.9007),
    (-3.0421, -0.1518),
    (-2.8065, 2.8065),
    (0.5445, 4.5169),
    (-3.0159, 3.0159),
)


def validate_auto_waypoints(
    waypoints: Sequence[Sequence[float]] = AUTO_WAYPOINTS,
) -> None:
    """Raise if the automatic trajectory is malformed or outside FR3 limits."""
    if len(waypoints) != 12:
        raise ValueError(f"automatic calibration requires 12 waypoints, got {len(waypoints)}")
    for waypoint_index, waypoint in enumerate(waypoints, start=1):
        if len(waypoint) != len(JOINT_NAMES):
            raise ValueError(f"waypoint {waypoint_index} must contain seven joints")
        for joint_index, (position, limits) in enumerate(
            zip(waypoint, FR3_JOINT_LIMITS), start=1
        ):
            low, high = limits
            if not math.isfinite(position) or not low + 0.02 <= position <= high - 0.02:
                raise ValueError(
                    f"waypoint {waypoint_index} joint {joint_index} is outside its safe range"
                )


validate_auto_waypoints()
